name: Metrics
on:
  schedule:
    - cron: 42 0 * * *
  push: {branches: ["main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          repositories_affiliations: owner, collaborator, organization_member
          repositories: 1000
          plugin_achievements: true
          plugin_achievements_ignored: stargazer, developer, forker, member, automator, follower, deployer, verified, worker
          base: header, repositories, metadata
          plugin_reactions: true
          plugin_reactions_limit: 1000
